<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        $now = now();

        $templates = [
            ['key' => 'welcome', 'name' => 'Welcome Email', 'description' => 'Sent to new users after registration.', 'subject' => 'Welcome to NADA!', 'greeting' => 'Hello {{user_name}}!', 'body' => "Welcome to the National Acupuncture Detoxification Association membership portal.\nWe are thrilled to have you join our community of dedicated practitioners.", 'action_text' => 'Visit Your Dashboard', 'action_url' => '/dashboard', 'outro' => 'If you have any questions, please do not hesitate to reach out to our support team.', 'available_variables' => json_encode(['user_name', 'user_email'])],
            ['key' => 'subscription_confirmed', 'name' => 'Subscription Confirmed', 'description' => 'Sent when a membership subscription is created.', 'subject' => 'Subscription Confirmed', 'greeting' => 'Hello {{user_name}}!', 'body' => "Your NADA membership subscription has been confirmed.\nPlan: {{plan_name}}\nStatus: Active", 'action_text' => 'View Membership', 'action_url' => '/membership', 'outro' => 'Thank you for becoming a NADA member!', 'available_variables' => json_encode(['user_name', 'plan_name'])],
            ['key' => 'subscription_renewed', 'name' => 'Membership Renewed', 'description' => 'Sent when a membership subscription is renewed.', 'subject' => 'Membership Renewed', 'greeting' => 'Hello {{user_name}}!', 'body' => "Your NADA membership has been successfully renewed.\nPlan: {{plan_name}}\nNext renewal date: {{renewal_date}}", 'action_text' => 'View Membership', 'action_url' => '/membership', 'outro' => 'Thank you for continuing your membership with NADA!', 'available_variables' => json_encode(['user_name', 'plan_name', 'renewal_date'])],
            ['key' => 'subscription_canceled', 'name' => 'Subscription Canceled', 'description' => 'Sent when a membership subscription is canceled.', 'subject' => 'Subscription Canceled', 'greeting' => 'Hello {{user_name}},', 'body' => "Your NADA membership subscription has been canceled.\nYour access will remain active until: {{expiry_date}}\nYou can resubscribe at any time to regain full membership benefits.", 'action_text' => 'Resubscribe', 'action_url' => '/membership', 'outro' => 'We hope to see you back soon.', 'available_variables' => json_encode(['user_name', 'expiry_date'])],
            ['key' => 'payment_failed', 'name' => 'Payment Failed', 'description' => 'Sent when a payment attempt fails.', 'subject' => 'Payment Failed - Action Required', 'greeting' => 'Hello {{user_name}},', 'body' => "We were unable to process your recent payment.\nAmount: {{amount}}\nPlease update your payment method to avoid any interruption to your membership.", 'action_text' => 'Update Payment Method', 'action_url' => '/membership/billing', 'outro' => 'If you believe this is an error, please contact our support team.', 'available_variables' => json_encode(['user_name', 'amount'])],
            ['key' => 'payment_method_updated', 'name' => 'Payment Method Updated', 'description' => 'Sent when a payment method is changed.', 'subject' => 'Payment Method Updated', 'greeting' => 'Hello {{user_name}},', 'body' => "Your payment method has been successfully updated.\nAll future charges will be applied to your new payment method.", 'action_text' => 'View Account', 'action_url' => '/membership', 'outro' => 'If you did not make this change, please contact our support team immediately.', 'available_variables' => json_encode(['user_name'])],
            ['key' => 'training_registered', 'name' => 'Training Registration Confirmed', 'description' => 'Sent when a user registers for a training.', 'subject' => 'Training Registration Confirmed', 'greeting' => 'Hello {{user_name}}!', 'body' => "Your training registration has been confirmed.\nTraining: {{training_title}}\nDate: {{training_date}}\nLocation: {{training_location}}", 'action_text' => 'View Training Details', 'action_url' => '/trainings/{{training_id}}', 'outro' => 'We look forward to seeing you there!', 'available_variables' => json_encode(['user_name', 'training_title', 'training_date', 'training_location', 'training_id'])],
            ['key' => 'training_reminder', 'name' => 'Training Reminder', 'description' => 'Sent 24 hours before a training session.', 'subject' => 'Training Reminder - Tomorrow!', 'greeting' => 'Hello {{user_name}}!', 'body' => "This is a friendly reminder that your NADA training session is tomorrow.\nTraining: {{training_title}}\nDate: {{training_date}}\nLocation: {{training_location}}", 'action_text' => 'View Training Details', 'action_url' => '/trainings/{{training_id}}', 'outro' => 'Please arrive on time and bring any required materials.', 'available_variables' => json_encode(['user_name', 'training_title', 'training_date', 'training_location', 'training_id'])],
            ['key' => 'training_completed', 'name' => 'Training Completed', 'description' => 'Sent when a user completes a training.', 'subject' => 'Training Completed!', 'greeting' => 'Congratulations {{user_name}}!', 'body' => "You have successfully completed your NADA training session.\nTraining: {{training_title}}\nYour certificate will be available shortly.", 'action_text' => 'View Your Dashboard', 'action_url' => '/dashboard', 'outro' => 'Thank you for your commitment to the NADA protocol.', 'available_variables' => json_encode(['user_name', 'training_title'])],
            ['key' => 'training_canceled', 'name' => 'Training Canceled', 'description' => 'Sent to registered attendees when a training is canceled.', 'subject' => 'Training Canceled', 'greeting' => 'Hello {{user_name}},', 'body' => "We regret to inform you that the following training session has been canceled.\nTraining: {{training_title}}\nOriginally scheduled: {{training_date}}\nIf you have already paid, a refund will be processed automatically.", 'action_text' => 'Browse Trainings', 'action_url' => '/trainings', 'outro' => 'We apologize for any inconvenience.', 'available_variables' => json_encode(['user_name', 'training_title', 'training_date'])],
            ['key' => 'certificate_ready', 'name' => 'Certificate Ready', 'description' => 'Sent when a certificate is issued.', 'subject' => 'Your NADA Certificate is Ready!', 'greeting' => 'Congratulations {{user_name}}!', 'body' => "Your NADA certificate has been issued and is ready for download.\nCertificate Number: {{certificate_number}}", 'action_text' => 'Download Certificate', 'action_url' => '/certificates/{{certificate_id}}', 'outro' => 'Thank you for your dedication to the NADA protocol.', 'available_variables' => json_encode(['user_name', 'certificate_number', 'certificate_id'])],
            ['key' => 'discount_requested', 'name' => 'Discount Requested (Admin)', 'description' => 'Sent to admins when a discount request is submitted.', 'subject' => 'New Discount Request', 'greeting' => 'Hello Admin,', 'body' => "A new discount request has been submitted and requires your review.\nRequested by: {{requester_name}}\nEmail: {{requester_email}}\nReason: {{reason}}", 'action_text' => 'Review Request', 'action_url' => '/admin/discount-requests/{{request_id}}', 'outro' => 'Please review and approve or deny this request.', 'available_variables' => json_encode(['requester_name', 'requester_email', 'reason', 'request_id'])],
            ['key' => 'discount_approved', 'name' => 'Discount Approved', 'description' => 'Sent when a discount request is approved.', 'subject' => 'Discount Request Approved!', 'greeting' => 'Hello {{user_name}}!', 'body' => "Great news! Your discount request has been approved.\nDiscount Code: {{discount_code}}\nYou can apply this code during checkout to receive your discount.", 'action_text' => 'View Membership Plans', 'action_url' => '/membership', 'outro' => 'Thank you for being part of the NADA community!', 'available_variables' => json_encode(['user_name', 'discount_code'])],
            ['key' => 'discount_denied', 'name' => 'Discount Denied', 'description' => 'Sent when a discount request is denied.', 'subject' => 'Discount Request Update', 'greeting' => 'Hello {{user_name}},', 'body' => "We have reviewed your discount request and unfortunately we are unable to approve it at this time.\nIf you believe this decision was made in error or if your circumstances have changed, please feel free to submit a new request.", 'action_text' => 'View Membership Plans', 'action_url' => '/membership', 'outro' => 'Thank you for your understanding.', 'available_variables' => json_encode(['user_name'])],
            ['key' => 'trainer_application_submitted', 'name' => 'Trainer Application Submitted (Admin)', 'description' => 'Sent to admins when a trainer application is submitted.', 'subject' => 'New Trainer Application', 'greeting' => 'Hello Admin,', 'body' => "A new trainer application has been submitted and requires your review.\nApplicant: {{applicant_name}}\nEmail: {{applicant_email}}", 'action_text' => 'Review Application', 'action_url' => '/admin/trainer-applications/{{application_id}}', 'outro' => 'Please review and process this application.', 'available_variables' => json_encode(['applicant_name', 'applicant_email', 'application_id'])],
            ['key' => 'trainer_application_approved', 'name' => 'Trainer Application Approved', 'description' => 'Sent when a trainer application is approved.', 'subject' => 'Trainer Application Approved!', 'greeting' => 'Congratulations {{user_name}}!', 'body' => "Your application to become a NADA trainer has been approved!\nYou now have access to trainer features, including the ability to create and manage training sessions.", 'action_text' => 'Go to Trainer Dashboard', 'action_url' => '/trainer/dashboard', 'outro' => 'Welcome to the NADA trainer community!', 'available_variables' => json_encode(['user_name'])],
            ['key' => 'trainer_application_denied', 'name' => 'Trainer Application Denied', 'description' => 'Sent when a trainer application is denied.', 'subject' => 'Trainer Application Update', 'greeting' => 'Hello {{user_name}},', 'body' => "We have reviewed your trainer application and unfortunately we are unable to approve it at this time.\nThis may be due to insufficient training hours or other requirements that have not yet been met.\nYou are welcome to reapply once you have completed the necessary requirements.", 'action_text' => 'View Requirements', 'action_url' => '/trainers/apply', 'outro' => 'Thank you for your interest in becoming a NADA trainer.', 'available_variables' => json_encode(['user_name'])],
            ['key' => 'clinical_submitted', 'name' => 'Clinical Submitted (Admin)', 'description' => 'Sent to admins when a clinical submission is received.', 'subject' => 'New Clinical Submission', 'greeting' => 'Hello Admin,', 'body' => "A new clinical submission has been received and requires your review.\nSubmitted by: {{submitter_name}}\nEmail: {{submitter_email}}", 'action_text' => 'Review Submission', 'action_url' => '/admin/clinicals/{{clinical_id}}', 'outro' => 'Please review this clinical submission at your earliest convenience.', 'available_variables' => json_encode(['submitter_name', 'submitter_email', 'clinical_id'])],
            ['key' => 'payout_received', 'name' => 'Payout Received', 'description' => 'Sent to trainers when a payout is processed.', 'subject' => 'Payout Received!', 'greeting' => 'Hello {{user_name}}!', 'body' => "A payout has been processed to your account.\nAmount: {{amount}}\nThe funds should appear in your bank account within a few business days.", 'action_text' => 'View Payout History', 'action_url' => '/trainer/payouts', 'outro' => 'Thank you for being a valued NADA trainer!', 'available_variables' => json_encode(['user_name', 'amount'])],
            ['key' => 'invoice_created', 'name' => 'New Invoice', 'description' => 'Sent to members when a new invoice is created.', 'subject' => 'New Invoice {{invoice_number}}', 'greeting' => 'Hello {{user_name}},', 'body' => "A new invoice has been created for your account.\nInvoice: {{invoice_number}}\nAmount Due: {{amount_due}}\nPlease review and submit payment at your earliest convenience.", 'action_text' => 'View Invoice', 'action_url' => '/invoices/{{invoice_id}}', 'outro' => 'If you have any questions about this invoice, please contact our support team.', 'available_variables' => json_encode(['user_name', 'invoice_number', 'amount_due', 'invoice_id'])],
        ];

        foreach ($templates as $template) {
            // Skip if already exists (idempotent)
            if (DB::table('email_templates')->where('key', $template['key'])->exists()) {
                continue;
            }

            DB::table('email_templates')->insert(array_merge($template, [
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ]));
        }
    }

    public function down(): void
    {
        DB::table('email_templates')->whereIn('key', [
            'welcome', 'subscription_confirmed', 'subscription_renewed', 'subscription_canceled',
            'payment_failed', 'payment_method_updated', 'training_registered', 'training_reminder',
            'training_completed', 'training_canceled', 'certificate_ready', 'discount_requested',
            'discount_approved', 'discount_denied', 'trainer_application_submitted',
            'trainer_application_approved', 'trainer_application_denied', 'clinical_submitted',
            'payout_received', 'invoice_created',
        ])->delete();
    }
};
